# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rprr_arm_controller

  rprr_arm_controller:
    type: FollowJointTrajectory
    joints:
      - jnt2
      - jnt1
      - jnt3
      - jnt4