# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rprr_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rprr_arm_controller:
  ros__parameters:
    joints:
      - jnt2
      - jnt1
      - jnt3
      - jnt4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity